#!/bin/bash
set -e

#git clone --no-checkout "$GSTREAMER_REPOSITORY"

#git checkout "$GSTREAMER_CHECKOUT"

git clone --depth 1 --branch ${GST_VERSION} https://github.com/GStreamer/gstreamer
#pushd gstreamer

# rtpvp8depay: Also wait for keyframes if configured so if incomplete frames are detected
#wget -O - https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/2947.diff | git apply
#popd

#git clone --no-checkout "$GSTREAMER_CEF_REPOSITORY"
#pushd gstcefsrc
#git checkout "$GSTREAMER_CEF_CHECKOUT"
#popd
