build_from:
  aarch64: "ghcr.io/hassio-addons/base:13.0.1"
  amd64: "ghcr.io/hassio-addons/base:13.0.1"
  armv7: "ghcr.io/hassio-addons/base:13.0.1"
  amd64: "ghcr.io/hassio-addons/base:13.0.1"
  i386: "ghcr.io/hassio-addons/base:13.0.1"
codenotary:
 signer: "bittles.github@gmail.com"
