---
name: Vaultwarden (Bitwarden) URL Fork
version: v0.18.0
slug: bitwarden-urlfork
description: Open source password management solution
url: https://github.com/bittles/Hassio-addons
codenotary: codenotary@frenck.dev
#webui: "[PROTO:ssl]://[PROTO:host_and_port]"
ingress: true
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Vaultwarden Web interface (not needed for ingress)
map:
  - ssl
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
#  host_and_port: localhost:7277
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  request_size_limit: int?
#  host_and_port: str?
