language: python
# Enable python 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install pipenv
  - pipenv install --dev

script: pipenv run python -m pytest --cov=./ tests

after_success:
  - codecov