image: homeassistant/{arch}-base
shadow_repository: ghcr.io/home-assistant
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.16"
  amd64: "ghcr.io/home-assistant/amd64-base:3.16"
  armhf: "ghcr.io/home-assistant/armhf-base:3.16"
  armv7: "ghcr.io/home-assistant/armv7-base:3.16"
  i386: "ghcr.io/home-assistant/i386-base:3.16"
codenotary:
  signer: notary@home-assistant.io
args:
  BASHIO_VERSION: 0.14.3
  TEMPIO_VERSION: 2021.09.0
  S6_OVERLAY_VERSION: 3.1.2.1
  JEMALLOC_VERSION: 5.3.0
labels:
  io.hass.base.name: alpine
  org.opencontainers.image.source: https://github.com/home-assistant/docker-base