image: homeassistant/{arch}-base
shadow_repository: ghcr.io/home-assistant
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
codenotary:
  signer: notary@home-assistant.io
args:
  BASHIO_VERSION: 0.14.3
  TEMPIO_VERSION: 2021.09.0
  S6_OVERLAY_VERSION: 3.1.2.1
  JEMALLOC_VERSION: 5.3.0
labels:
  io.hass.base.name: alpine
  org.opencontainers.image.source: https://github.com/home-assistant/docker-base