build_from:
  armhf: "ghcr.io/hassio-addons/base-python/armhf:9.0.1"
  armv7: "ghcr.io/hassio-addons/base-python/armv7:9.0.1"
  aarch64: "ghcr.io/hassio-addons/base-python/aarch64:9.0.1"
  amd64: "ghcr.io/hassio-addons/base-python/amd64:9.0.1"
  i386: "ghcr.io/hassio-addons/base-python/i386:9.0.1"
