build_from:
  armhf: "ghcr.io/hassio-addons/base-python/armhf:7.2.0"
  armv7: "ghcr.io/hassio-addons/base-python/armv7:7.2.0"
  aarch64: "ghcr.io/hassio-addons/base-python/aarch64:7.2.0"
  amd64: "ghcr.io/hassio-addons/base-python/amd64:7.2.0"
  i386: "ghcr.io/hassio-addons/base-python/i386:7.2.0"
