name: Bumper
version: 1.0.0
slug: Bumper
description: Local replacement server for Ecovacs robots.
url: https://github.com/Poeschl/Hassio-Addons/tree/main/valetudo-mapper
arch:
  - armhf
  - armv7
  - aarch64
  - arm64v8
  - amd64
  - i386
image: ghcr.io/poeschl/ha-valetudo-mapper-{arch}
init: false
ports:
  3000/tcp: null
ports_description:
  3000/tcp: Port serving the floor plan (Not required for Ingress)
ingress: true

ingress_port: 3000

ingress_entry: api/map/image

panel_title: Valetudo RE Floorplan

panel_icon: mdi:floor-plan

map:
  - ssl


schema:
  mapSettings:
    drawPath: bool?
    drawCharger: bool?
    drawRobot: bool?
    drawCurrentlyCleanedZones: bool?
    drawCurrentlyCleanedBlocks: bool?
    drawForbiddenZones: bool?
    drawVirtualWalls: bool?
    scale: int(0,)?
    gradientBackground: bool?
    autoCrop: int?
    crop_x1: int?
    crop_y1: int?
    crop_x2: int?
    crop_y2: int?
    rotate: int?
  mapColors:
    background: match((#(?:[0-9a-fA-F]{2}){2,4}$|(#[0-9a-fA-F]{3}$)|(rgb|hsl)a?\((-?\d+%?[,\s]+){2,3}\s*[\d\.]+%?\)$|black$|silver$|gray$|whitesmoke$|maroon$|red$|purple$|fuchsia$|green$|lime$|olivedrab$|yellow$|navy$|blue$|teal$|aquamarine$|orange$|aliceblue$|antiquewhite$|aqua$|azure$|beige$|bisque$|blanchedalmond$|blueviolet$|brown$|burlywood$|cadetblue$|chartreuse$|chocolate$|coral$|cornflowerblue$|cornsilk$|crimson$|darkblue$|darkcyan$|darkgoldenrod$|darkgray$|darkgreen$|darkgrey$|darkkhaki$|darkmagenta$|darkolivegreen$|darkorange$|darkorchid$|darkred$|darksalmon$|darkseagreen$|darkslateblue$|darkslategray$|darkslategrey$|darkturquoise$|darkviolet$|deeppink$|deepskyblue$|dimgray$|dimgrey$|dodgerblue$|firebrick$|floralwhite$|forestgreen$|gainsboro$|ghostwhite$|goldenrod$|gold$|greenyellow$|grey$|honeydew$|hotpink$|indianred$|indigo$|ivory$|khaki$|lavenderblush$|lavender$|lawngreen$|lemonchiffon$|lightblue$|lightcoral$|lightcyan$|lightgoldenrodyellow$|lightgray$|lightgreen$|lightgrey$|lightpink$|lightsalmon$|lightseagreen$|lightskyblue$|lightslategray$|lightslategrey$|lightsteelblue$|lightyellow$|limegreen$|linen$|mediumaquamarine$|mediumblue$|mediumorchid$|mediumpurple$|mediumseagreen$|mediumslateblue$|mediumspringgreen$|mediumturquoise$|mediumvioletred$|midnightblue$|mintcream$|mistyrose$|moccasin$|navajowhite$|oldlace$|olive$|orangered$|orchid$|palegoldenrod$|palegreen$|paleturquoise$|palevioletred$|papayawhip$|peachpuff$|peru$|pink$|plum$|powderblue$|rosybrown$|royalblue$|saddlebrown$|salmon$|sandybrown$|seagreen$|seashell$|sienna$|skyblue$|slateblue$|slategray$|slategrey$|snow$|springgreen$|steelblue$|tan$|thistle$|tomato$|transparent$|turquoise$|violet$|wheat$|white$|yellowgreen$|rebeccapurple$))?
  mqtt:
    broker_url: match(^mqtts?://(.+:.+@)?[^:@]+(:[0-9]+)?$)
    caPath: str
    mapDataTopic: str
    minMillisecondsBetweenMapUpdates: int
    publishMapImage: bool
    publishMapData: bool
options:
  mapSettings:
    drawPath: true
    drawCharger: true
    drawRobot: true
    drawCurrentlyCleanedZones: false
    drawCurrentlyCleanedBlocks: false
    drawForbiddenZones: true
    drawVirtualWalls: true
    scale: 4
    gradientBackground: true
    autoCrop: 20
  mapColors: {}
  mqtt:
    identifier: rockrobo
    topicPrefix: valetudo
    autoconfPrefix: homeassistant
    broker_url: mqtt://user:pass@foobar.example
    caPath: ""
    mapDataTopic: valetudo/rockrobo/map_data
    minMillisecondsBetweenMapUpdates: 10000
    publishMapImage: true
    publishMapData: false
