name: "Bumper"
version: "1.0.0"
slug: "bumper"
description: "Local replacement server for Ecovacs robots."
url: https://github.com/bittles/Hassio-addons/tree/master/bumper
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  443/tcp: 443
  5223/tcp: 5223
  8007/tcp: 8007
  8883/tcp: 8883
ports_description:
  443/tcp: Port serving requests from robots to https://x.ecovacs.com
  5223/tcp: Port serving XMPP server
  8007/tcp: Port serving helper to assign server to robot
  8883/tcp: Port serving bumper MQTT server
environment:
  PGID: "1000"
  PUID: "1000"
  BUMPER_DATA: /share/bumper-data
  BUMPER_CERTS: /ssl/bumper-certs
  LOG_TO_STDOUT: "True"
map:
  - ssl:rw
  - share:rw
schema:
  BUMPER_ANNOUNCE_IP: match(([0-9])+(.+))
  TZ: str
  BUMPER_LISTEN: match(([0-9])+(.+))?
  BUMPER_DEBUG: bool?
  ENABLE_XMPP: bool
  ENABLE_MQTT: bool
options:
  BUMPER_ANNOUNCE_IP: 
  TZ: Europe/Rome
  BUMPER_LISTEN: 0.0.0.0
  BUMPER_DEBUG: false
  ENABLE_XMPP: true
  ENABLE_MQTT: true
