"name": "Inadyn Bittles fork Arm64"
"slug": "inadyn-bittles-arm64"
"url": https://github.com/bittles/Hassio-addons
"version": "2.10.0.2"
"apparmor": true
"arch":
  - aarch64
"codenotary": "bittles.github@gmail.com"
"description": "Inadyn is a small and simple Dynamic DNS, DDNS, client with HTTPS support. A large number of dynamic dns providers are supported (https://github.com/troglobit/inadyn#supported-providers). For those that are not, you can use a custom provider as per this project's documentation (https://github.com/nalipaz/hassio-addons/blob/master/README.md)"
"host_network": true
#"image": "bittles999/inadynfork-arm64"
"map":
  - ssl
  - share:rw
"options":
  providers:
    hostname: dynamic-subdomain.example.com
    password: password
    provider: yourprovider
    username: username
"schema":
  allow_ipv6: bool?
  fake_address: bool?
  forced_update: int?
  iface: str?
  iterations: int?
  period: int?
  secure_ssl: bool?
  verify_address: bool?
  providers:
    - append_myip: bool?
      checkip_command: str?
      checkip_path: str?
      checkip_server: str?
      checkip_ssl: bool?
      custom_provider: bool?
      ddns_path: str?
      ddns_server: str?
      hostname: str
      password: str?
      provider: str
      proxied: bool?
      ssl: bool?
      ttl: int?
      user_agent: str?
      username: str
      wildcard: bool?
