---
name: Vaultwarden (Bitwarden) Ingress Arm64 Only
version: 0.19.0.6
slug: bitwarden-ingress-arm64
description: Open source password management solution
url: https://github.com/bittles/Hassio-addons
image: bittles999/vaultwarden-ingress-arm64
init: false
ingress: true
ingress_stream: true
panel_icon: mdi:form-textbox-password
#ingress_port: 8089
arch:
  - aarch64
ports:
  6942/tcp: null
ports_description:
  6942/tcp: Vaultwarden Web interface (not needed for ingress, only for /admin page access)
map:
  - ssl
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  request_size_limit: int?

