name: "Bumper Arm64"
version: "1.2.2"
slug: "bumper-arm64"
apparmor: true
description: "Local replacement server for Ecovacs robots."
image: bittles999/bumper-arm64
url: https://github.com/bittles/Hassio-addons/tree/master/bumper
startup: services
arch:
  - aarch64
init: false
ports:
  443/tcp: 443
  5223/tcp: 5223
  8007/tcp: 8007
  8883/tcp: 8883
ports_description:
  443/tcp: Port serving requests from robots to https://x.ecovacs.com
  5223/tcp: Port serving XMPP server
  8007/tcp: Port serving helper to assign server to robot
  8883/tcp: Port serving bumper MQTT server
environment:
  PGID: "1000"
  PUID: "1000"
  BUMPER_DATA: /share/bumper_data
  BUMPER_CERTS: /ssl/bumper_certs
  LOG_TO_STDOUT: "True"
map:
  - ssl:rw
  - share:rw
schema:
  announce_ip: match(([0-9])+(.+))
  listen_ip: match(([0-9])+(.+))
  time_zone: str
  debug_logs: bool?
  disable_xmpp_server: bool?
  disable_mqtt_server: bool?
options:
  announce_ip: null
  listen_ip: 0.0.0.0
  time_zone: America/New_York
